'use strict';

// ─────────────────────────────────────────────
// CONSTANTS
// ─────────────────────────────────────────────
const BS = 'https://www.brandonsanderson.com/cdn/shop/files/';
const WP = 'https://upload.wikimedia.org/wikipedia/en/';

// ─────────────────────────────────────────────
// I18N LOCALIZATION SYSTEM
// ─────────────────────────────────────────────
const TRANSLATIONS = {
  en: {
    pageTitle: 'The Cosmere Timeline',
    title: 'THE COSMERE',
    subtitle: 'Shardworld Timeline · approximate in-universe chronology',
    rightsNotice: 'All rights to the books and book covers belong to their rightful owners.',
    allWorlds: 'ALL WORLDS',
    earlier: 'EARLIER',
    later: 'LATER',
    jumpToStart: 'Jump to start',
    jumpToEnd: 'Jump to end',
    timelinePosition: 'Timeline position',
    planetFilter: 'Planet filter',
    forthcoming: '✦ FORTHCOMING',
    yolen: 'Yolen',
    taldain: 'Taldain',
    sel: 'Sel',
    scadrial1: 'Scadrial — Era 1',
    nalthis: 'Nalthis',
    threnody: 'Threnody',
    roshar: 'Roshar',
    scadrial2: 'Scadrial — Era 2',
    lumar: 'Lumar (Tress)',
    komashi: 'Komashi (Yumi)',
    fots: 'First of the Sun',
    canticle: 'Canticle (Sunlit Man)',
  },
  uk: {
    pageTitle: 'Хронологія Космеру',
    title: 'КОСМЕР',
    subtitle: 'Часова шкала світів Шардів · приблизна хронологія всесвіту',
    rightsNotice: 'Усі права на книги та обкладинки книг належать їхнім правовласникам.',
    allWorlds: 'ВСІ СВІТИ',
    earlier: 'РАНІШЕ',
    later: 'ПІЗНІШЕ',
    jumpToStart: 'Перейти на початок',
    jumpToEnd: 'Перейти в кінець',
    timelinePosition: 'Позиція на часовій шкалі',
    planetFilter: 'Фільтр за планетою',
    forthcoming: '✦ НЕЗАБАРОМ',
    yolen: 'Йолен',
    taldain: 'Талдаїн',
    sel: 'Сел',
    scadrial1: 'Скадріаль — Ера 1',
    nalthis: 'Нальтіс',
    threnody: 'Терафія',
    roshar: 'Рошар',
    scadrial2: 'Скадріаль — Ера 2',
    lumar: 'Лумар (Тресс)',
    komashi: 'Комаші (Юмі)',
    fots: 'Перший від Сонця',
    canticle: 'Канон (Людина сонячного світла)',
    // Book titles English
    dragonsteel: 'Dragonsteel',
    theSilenceDivine: 'The Silence Divine',
    whiteSand: 'White Sand',
    elantris: 'Elantris',
    hopeOfElantris: 'Hope of Elantris',
    theEmperorsSoul: "The Emperor's Soul",
    elantrisBook2: 'Elantris Book 2',
    elantrisBook3: 'Elantris Book 3',
    theEleventhMetal: 'The Eleventh Metal',
    theFinalEmpire: 'The Final Empire',
    secretHistory: 'Secret History',
    wellOfAscension: 'Well of Ascension',
    heroOfAges: 'Hero of Ages',
    shadowsForSilence: 'Shadows for Silence',
    warbreaker: 'Warbreaker',
    theWayOfKings: 'The Way of Kings',
    wordsOfRadiance: 'Words of Radiance',
    edgedancer: 'Edgedancer',
    oathbringer: 'Oathbringer',
    dawnshard: 'Dawnshard',
    rhythmOfWar: 'Rhythm of War',
    windAndTruth: 'Wind and Truth',
    alloyOfLaw: 'Alloy of Law',
    allomancerJak: 'Allomancer Jak',
    shadowsOfSelf: 'Shadows of Self',
    bandsOfMourning: 'Bands of Mourning',
    theLostMetal: 'The Lost Metal',
    tressOfTheEmeraldSea: 'Tress of the Emerald Sea',
    yumiAndNightmarePainter: 'Yumi & Nightmare Painter',
    sixthOfTheDusk: 'Sixth of the Dusk',
    islesOfTheEmberdark: 'Isles of the Emberdark',
    theSunlitMan: 'The Sunlit Man',
    elsecaller: 'Elsecaller',
    kingLopenFirstOfAlethkar: 'King Lopen the First of Alethkar',
    horneater: 'Horneater',
    whiteSandProse: 'White Sand (Prose)',
    warbreakerSequel: 'Warbreaker Sequel',
    ghostbloodsBook1: 'Ghostbloods Book 1',
    ghostbloodsBook2: 'Ghostbloods Book 2',
    ghostbloodsBook3: 'Ghostbloods Book 3',
    // Book titles Ukrainian
    dragonsteel_uk: 'Драконна сталь',
    theSilenceDivine_uk: 'Божественна тиша',
    whiteSand_uk: 'Білий пісок',
    elantris_uk: 'Елантріс',
    hopeOfElantris_uk: 'Надія Елантріса',
    theEmperorsSoul_uk: 'Душа empereur',
    elantrisBook2_uk: 'Елантріс: Книга 2',
    elantrisBook3_uk: 'Елантріс: Книга 3',
    theEleventhMetal_uk: 'Одинадцятий метал',
    theFinalEmpire_uk: 'З-імли-народжені',
    secretHistory_uk: 'Таємна історія',
    wellOfAscension_uk: 'Джерело Вознесіння',
    heroOfAges_uk: 'Герой віків',
    shadowsForSilence_uk: 'Тіні мовчання',
    warbreaker_uk: 'Підбивач миру',
    theWayOfKings_uk: 'Шлях королів',
    wordsOfRadiance_uk: 'Слова Променистого ордену',
    edgedancer_uk: 'Танцівниця на межі',
    oathbringer_uk: 'Присяжник',
    dawnshard_uk: 'Уламок світанку',
    rhythmOfWar_uk: 'Ритм війни',
    windAndTruth_uk: 'Вітер та Істина',
    alloyOfLaw_uk: 'Сплав законів',
    allomancerJak_uk: 'Алломант Джек',
    shadowsOfSelf_uk: 'Тіні себе',
    bandsOfMourning_uk: 'Браслети жалоби',
    theLostMetal_uk: 'Втрачений метал',
    tressOfTheEmeraldSea_uk: 'Тресс зі Смарагдового моря',
    yumiAndNightmarePainter_uk: 'Юмі та художник кошмарів',
    sixthOfTheDusk_uk: 'Шостий від сутінків',
    islesOfTheEmberdark_uk: 'Острови теплого морока',
    theSunlitMan_uk: 'Людина сонячного світла',
    elsecaller_uk: 'Elsecaller',
    kingLopenFirstOfAlethkar_uk: 'King Lopen the First of Alethkar',
    horneater_uk: 'Horneater',
    whiteSandProse_uk: 'Білий пісок (прозова версія)',
    warbreakerSequel_uk: 'Сиквел Warbreaker',
    ghostbloodsBook1_uk: 'Привидокровні: Книга 1',
    ghostbloodsBook2_uk: 'Привидокровні: Книга 2',
    ghostbloodsBook3_uk: 'Привидокровні: Книга 3',
    // Book blurbs English
    'dragonsteel_blurb': "Unpublished. Hoid's origin story. The Shattering of Adonalsium happens on Yolen.",
    'theSilenceDivine_blurb': 'Unpublished novella set on Yolen. Explores its unique, separate magic system.',
    'whiteSand_blurb': "Graphic novel trilogy. Sand mastery on a tidally locked world. Khriss's home planet.",
    'elantris_blurb': 'First published Cosmere novel. Aons and the Dor. A city of fallen Elantrians.',
    'hopeOfElantris_blurb': "Short story. The climax of Elantris from Ashe the seon's POV.",
    'theEmperorsSoul_blurb': "Hugo Award winner. A Forger has 100 days to recreate an Emperor's soul.",
    'elantrisBook2_blurb': "Forthcoming. 10 years after Elantris, set in Fjorden. Kiin's children as POVs.",
    'elantrisBook3_blurb': 'Forthcoming finale of the Elantris trilogy.',
    'theEleventhMetal_blurb': 'Short story prequel. Follows young Kelsier training under a mysterious Allomancer.',
    'theFinalEmpire_blurb': 'Ash falls forever. The Lord Ruler reigns. Vin discovers she is a Mistborn.',
    'secretHistory_blurb': "Novella. Kelsier's journey in the Cognitive Realm. Read after Hero of Ages.",
    'wellOfAscension_blurb': 'After the Lord Ruler. Armies besiege Luthadel. Elend rises to lead.',
    'heroOfAges_blurb': 'The Catacendre reshapes Scadrial. Harmony born from Ruin and Preservation.',
    'shadowsForSilence_blurb': 'Shades haunt dark forests. An innkeeper hunts a dangerous bounty to save her family.',
    'warbreaker_blurb': "BioChromatic Breath and the Returned gods. Vasher and Nightblood's origin on Nalthis.",
    'theWayOfKings_blurb': 'Kaladin, Shallan, Dalinar. The Knights Radiant must return.',
    'wordsOfRadiance_blurb': 'The Everstorm is coming. Szeth hunts. The Knights Radiant return.',
    'edgedancer_blurb': 'Novella. Lift slides through a doomed city while chasing Darkness.',
    'oathbringer_blurb': "Dalinar's dark past. The Everstorm merges realms. Battle of Thaylen City.",
    'dawnshard_blurb': 'Novella. Rysn and Lopen voyage to the forbidden isle of Aimia.',
    'rhythmOfWar_blurb': 'Fabrials. Navani bonds a spren. Urithiru is captured.',
    'windAndTruth_blurb': "Szeth's arc. Battle for Shinovar. End of Stormlight Archive Arc 1.",
    'alloyOfLaw_blurb': '~300 years after Catacendre. Industrial Scadrial. Wax and Wayne debut.',
    'allomancerJak_blurb': 'Short story. Pulp-adventure tales of Allomancer Jak in the Roughs.',
    'shadowsOfSelf_blurb': 'A Kandra is secretly murdering people. Revolution threatens Elendel.',
    'bandsOfMourning_blurb': "The Lord Ruler's legendary bracers surface. Southern Scadrians revealed.",
    'theLostMetal_blurb': "Trell / Autonomy revealed. Wax and Wayne's finale. Cosmere connections explode.",
    'tressOfTheEmeraldSea_blurb': 'A girl sails deadly spore seas to rescue the boy she loves. Narrated by Hoid.',
    'yumiAndNightmarePainter_blurb': 'Two people sharing one body across worlds. Spirit and technology collide.',
    'sixthOfTheDusk_blurb': "A lone trapper finds outsiders have discovered his isolated world.",
    'islesOfTheEmberdark_blurb': 'Direct sequel. Dusk and Leilani navigate a First of the Sun changed by outsiders.',
    'theSunlitMan_blurb': "Nomad (Sigzil) flees across worlds. Most cosmere-heavy Secret Project.",
    'elsecaller_blurb': 'Stormlight Lost Tales short fiction release connected to the Roshar timeline.',
    'kingLopenFirstOfAlethkar_blurb': 'Stormlight Lost Tales short fiction focused on Lopen in the Stormlight era.',
    'horneater_blurb': 'Planned Stormlight novella centered on Rock after Arc 1 events.',
    'whiteSandProse_blurb': 'Planned prose retelling of White Sand on Taldain. Current status: back burner.',
    'warbreakerSequel_blurb': 'Planned sequel set on Nalthis, continuing threads from Warbreaker.',
    'ghostbloodsBook1_blurb': 'Mistborn Era 3 (Ghostbloods) Book 1. Planned release: December 2028.',
    'ghostbloodsBook2_blurb': 'Mistborn Era 3 (Ghostbloods) Book 2. Planned release: December 2029.',
    'ghostbloodsBook3_blurb': 'Mistborn Era 3 (Ghostbloods) Book 3. Planned release: December 2030.',
    // Book years English
    'dragonsteel_year': 'Pre-Shattering · Year ~0',
    'theSilenceDivine_year': 'Pre-Shattering · Year ~0',
    'whiteSand_year': '~500 PS · Earliest published Cosmere',
    'elantris_year': '~1000 PS · Year 0 Arelish Reckoning',
    'hopeOfElantris_year': '~1000 PS (concurrent with Elantris)',
    'theEmperorsSoul_year': '~1000 PS · Sel, different region',
    'elantrisBook2_year': '~1010 PS · Planned 2029',
    'elantrisBook3_year': 'Planned 2030',
    'theEleventhMetal_year': '~3200 PS · Before Final Empire',
    'theFinalEmpire_year': '~3242 PS · Year 1000 of the Final Empire',
    'secretHistory_year': '~3242 PS (runs alongside Era 1)',
    'wellOfAscension_year': '~3243 PS · Year 1001 Final Empire',
    'heroOfAges_year': '~3244 PS · The Catacendre',
    'shadowsForSilence_year': '~3500 PS · Pre-Stormlight era',
    'warbreaker_year': '~3500 PS · Concurrent with early Stormlight',
    'theWayOfKings_year': '1174 SA (~3500 PS)',
    'wordsOfRadiance_year': '1174 SA',
    'edgedancer_year': '1174 SA · Between WoR & Oathbringer',
    'oathbringer_year': '1175 SA',
    'dawnshard_year': '1175 SA · Between Oath & RoW',
    'rhythmOfWar_year': '1175 SA',
    'windAndTruth_year': '1175 SA',
    'alloyOfLaw_year': '~342 VE · ~3542 PS',
    'allomancerJak_year': '~342 VE',
    'shadowsOfSelf_year': '~342 VE',
    'bandsOfMourning_year': '~342 VE',
    'theLostMetal_year': '~342 VE',
    'tressOfTheEmeraldSea_year': 'Far future · ~5000+ PS',
    'yumiAndNightmarePainter_year': 'Far future · ~5000+ PS',
    'sixthOfTheDusk_year': 'Far future · interplanetary travel era',
    'islesOfTheEmberdark_year': 'Far future · after Sixth of the Dusk · 2025',
    'theSunlitMan_year': 'Far future · latest chronologically',
    'elsecaller_year': '1175 SA · Stormlight Lost Tales',
    'kingLopenFirstOfAlethkar_year': '1175 SA · Stormlight Lost Tales',
    'horneater_year': 'Post-Wind and Truth · Planned',
    'whiteSandProse_year': '~500 PS · Planned prose edition',
    'warbreakerSequel_year': '~3500+ PS · Planned sequel era',
    'ghostbloodsBook1_year': '~350+ VE · Planned Dec 2028',
    'ghostbloodsBook2_year': '~350+ VE · Planned Dec 2029',
    'ghostbloodsBook3_year': '~350+ VE · Planned Dec 2030',
    // Book blurbs Ukrainian
    'dragonsteel_blurb_uk': 'Неопубліковано. Історія походження Хойда. Розкол Адоналсіума відбувається на Йолені.',
    'theSilenceDivine_blurb_uk': 'Неопублікована новела на Йолені. Досліджує його унікальну, окрему магічну систему.',
    'whiteSand_blurb_uk': 'Трилогія графічних романів. Майстерність керування піском на світі з припливним захопленням. Рідна планета Крісс.',
    'elantris_blurb_uk': 'Перший опублікований роман Космеру. Аони та Дор. Місто занепалих елантрійців.',
    'hopeOfElantris_blurb_uk': 'Оповідання. Кульмінація «Елантріса» з погляду сеона Еша.',
    'theEmperorsSoul_blurb_uk': 'Лауреат премії Г\'юго. У Фальсифікаторки є 100 днів, щоб відтворити душу Імператора.',
    'elantrisBook2_blurb_uk': 'Найскоро. Події через 10 років після «Елантріса», у Фйордені. Серед POV — діти Кііна.',
    'elantrisBook3_blurb_uk': 'Майбутній фінал трилогії «Елантріс».',
    'theEleventhMetal_blurb_uk': 'Оповідання-приквел. Молодий Келсьєр навчається в таємничого аломанса.',
    'theFinalEmpire_blurb_uk': 'Попіл падає вічно. Лорд-правитель царює. Він дізнається, що вона — млистороджена.',
    'secretHistory_blurb_uk': 'Новела. Подорож Келсьєра у Когнітивному царстві. Читати після «Героя віків».',
    'wellOfAscension_blurb_uk': 'Після загибелі Лорда-правителя. Армії облягають Лютадель. Еленд вчиться бути лідером.',
    'heroOfAges_blurb_uk': 'Катасендр змінює Скадріаль. Гармонія народжується з Руйнування та Збереження.',
    'shadowsForSilence_blurb_uk': 'Тіні переслідують темні ліси. Господиня заїзду полює на небезпечну здобич, щоб урятувати родину.',
    'warbreaker_blurb_uk': 'Біохроматичне Дихання та Повернені боги. Походження Вашера й Нічнокровця на Нальтісі.',
    'theWayOfKings_blurb_uk': 'Каладін, Шаллан і Далінар. Лицарі Сяйва мають повернутися.',
    'wordsOfRadiance_blurb_uk': 'Насувається Вічна буря. Сет полює. Лицарі Сяйва повертаються.',
    'edgedancer_blurb_uk': 'Новела. Ліфт ковзає крізь приречене місто, уникаючи Тьми.',
    'oathbringer_blurb_uk': 'Темне минуле Далінара. Вічна буря зливає царства. Битва за Тейлен-Сіті.',
    'dawnshard_blurb_uk': 'Новела. Рісн і Лопен вирушають на заборонений острів Аймія.',
    'rhythmOfWar_blurb_uk': 'Фабріалі. Навані налагоджує зв\'язок зі спреном. Уритіру захоплено.',
    'windAndTruth_blurb_uk': 'Арка Сета. Битва за Шиновар. Завершення 1-ї арки «Архіву Буресвітла».',
    'alloyOfLaw_blurb_uk': 'Близько 300 років після Катасендру. Індустріальний Скадріаль. Дебют Вакса і Вейна.',
    'allomancerJak_blurb_uk': 'Оповідання. Пульпові пригоди Аломанта Джека в Рафсах.',
    'shadowsOfSelf_blurb_uk': 'Кандра таємно вбиває людей. Еленделю загрожує революція.',
    'bandsOfMourning_blurb_uk': 'З\'являються легендарні браслети Лорда-правителя. Відкривається правда про Південний Скадріаль.',
    'theLostMetal_blurb_uk': 'Трелл / Автономія розкриті. Фінал Вакса й Вейна. Космерні зв\'язки виходять на перший план.',
    'tressOfTheEmeraldSea_blurb_uk': 'Дівчина пливе смертоносними морями спор, щоб урятувати коханого. Розповідає Хойд.',
    'yumiAndNightmarePainter_blurb_uk': 'Двоє людей ділять одне тіло через світи. Зіткнення духу й технологій.',
    'sixthOfTheDusk_blurb_uk': 'Самотній мисливець дізнається, що чужинці відкрили його ізольований світ.',
    'islesOfTheEmberdark_blurb_uk': 'Пряме продовження. Даск і Лейлані мандрують світом «Шостого від Сутінків», зміненим чужинцями.',
    'theSunlitMan_blurb_uk': 'Кочівник (Сігзіл) тікає крізь світи. Найбільш космерно насичений таємний проєкт.',
    'elsecaller_blurb_uk': 'Коротка проза зі Stormlight Lost Tales, пов\u2019язана з хронологією Рошару.',
    'kingLopenFirstOfAlethkar_blurb_uk': 'Коротка проза зі Stormlight Lost Tales про Лопена в епосі Архіву Буресвітла.',
    'horneater_blurb_uk': 'Запланована новела Архіву Буресвітла, зосереджена на Року після подій Арки 1.',
    'whiteSandProse_blurb_uk': 'Запланована прозова версія White Sand на Талдаїні. Поточний статус: відкладено.',
    'warbreakerSequel_blurb_uk': 'Запланований сиквел на Нальтісі, що продовжує сюжетні лінії Warbreaker.',
    'ghostbloodsBook1_blurb_uk': 'Mistborn Era 3 (Ghostbloods), Книга 1. Запланований реліз: грудень 2028.',
    'ghostbloodsBook2_blurb_uk': 'Mistborn Era 3 (Ghostbloods), Книга 2. Запланований реліз: грудень 2029.',
    'ghostbloodsBook3_blurb_uk': 'Mistborn Era 3 (Ghostbloods), Книга 3. Запланований реліз: грудень 2030.',
    // Book years Ukrainian
    'dragonsteel_year_uk': 'До Розколювання · Рік ~0',
    'theSilenceDivine_year_uk': 'До Розколювання · Рік ~0',
    'whiteSand_year_uk': '~500 ПР · Найранніший опублікований Космер',
    'elantris_year_uk': '~1000 ПР · Рік 0 Арелейського літочислення',
    'hopeOfElantris_year_uk': '~1000 ПР (одночасно з Елантрісом)',
    'theEmperorsSoul_year_uk': '~1000 ПР · Сел, інший регіон',
    'elantrisBook2_year_uk': '~1010 ПР · Запланована на 2029',
    'elantrisBook3_year_uk': 'Запланована на 2030',
    'theEleventhMetal_year_uk': '~3200 ПР · Перед Фінальною імпе рією',
    'theFinalEmpire_year_uk': '~3242 ПР · Рік 1000 Фінальної імперії',
    'secretHistory_year_uk': '~3242 ПР (паралельно з Ерою 1)',
    'wellOfAscension_year_uk': '~3243 ПР · Рік 1001 Фінальної імперії',
    'heroOfAges_year_uk': '~3244 ПР · Катаценда',
    'shadowsForSilence_year_uk': '~3500 ПР · До ери Шторму',
    'warbreaker_year_uk': '~3500 ПР · Одночасно з ранньою Шторм-архівом',
    'theWayOfKings_year_uk': '1174 СА (~3500 ПР)',
    'wordsOfRadiance_year_uk': '1174 СА',
    'edgedancer_year_uk': '1174 СА · Між ВР і Присяго приносцем',
    'oathbringer_year_uk': '1175 СА',
    'dawnshard_year_uk': '1175 СА · Між Присяго- й РВ',
    'rhythmOfWar_year_uk': '1175 СА',
    'windAndTruth_year_uk': '1175 СА',
    'alloyOfLaw_year_uk': '~342 ВЕ · ~3542 ПР',
    'allomancerJak_year_uk': '~342 ВЕ',
    'shadowsOfSelf_year_uk': '~342 ВЕ',
    'bandsOfMourning_year_uk': '~342 ВЕ',
    'theLostMetal_year_uk': '~342 ВЕ',
    'tressOfTheEmeraldSea_year_uk': 'Далеке майбутнє · ~5000+ ПР',
    'yumiAndNightmarePainter_year_uk': 'Далеке майбутнє · ~5000+ ПР',
    'sixthOfTheDusk_year_uk': 'Далеке майбутнє · ера міжпланетних подорожей',
    'islesOfTheEmberdark_year_uk': 'Далеке майбутнє · після Шостого від Сутінків · 2025',
    'theSunlitMan_year_uk': 'Далеке майбутнє · найпізніше хронологічно',
    'elsecaller_year_uk': '1175 СА · Stormlight Lost Tales',
    'kingLopenFirstOfAlethkar_year_uk': '1175 СА · Stormlight Lost Tales',
    'horneater_year_uk': 'Після Wind and Truth · заплановано',
    'whiteSandProse_year_uk': '~500 ПР · запланована прозова версія',
    'warbreakerSequel_year_uk': '~3500+ ПР · запланована ера сиквелу',
    'ghostbloodsBook1_year_uk': '~350+ ВЕ · заплановано на грудень 2028',
    'ghostbloodsBook2_year_uk': '~350+ ВЕ · заплановано на грудень 2029',
    'ghostbloodsBook3_year_uk': '~350+ ВЕ · заплановано на грудень 2030',
    // Era labels and years
    'era_yolen_label': 'Yolen · Pre-Shattering',
    'era_yolen_year': 'Year 0 (Shattering)',
    'era_taldain_label': 'Taldain · Earliest',
    'era_taldain_year': '~500 PS',
    'era_sel_label': 'Sel (Elantris era)',
    'era_sel_year': '~1000 PS',
    'era_scadrial1_label': 'Scadrial Era 1 · Mistborn',
    'era_scadrial1_year': '~3200–3250 PS',
    'era_threnody_label': 'Threnody / Nalthis',
    'era_threnody_year': '~3500 PS',
    'era_roshar_label': 'Roshar · Stormlight Arc 1',
    'era_roshar_year': '1174–1175 SA',
    'era_scadrial2_label': 'Scadrial Era 2',
    'era_scadrial2_year': '~342 VE',
    'era_future_label': 'Far Future · Secret Projects',
    'era_future_year': '~5000+ PS',
    // Era labels and years Ukrainian
    'era_yolen_label_uk': 'Йолен · До Розколювання',
    'era_yolen_year_uk': 'Рік 0 (Розколювання)',
    'era_taldain_label_uk': 'Талдаїн · Найраніше',
    'era_taldain_year_uk': '~500 ПР',
    'era_sel_label_uk': 'Сел (ера Елантріса)',
    'era_sel_year_uk': '~1000 ПР',
    'era_scadrial1_label_uk': 'Скадріаль Ера 1 · Помпилка',
    'era_scadrial1_year_uk': '~3200–3250 ПР',
    'era_threnody_label_uk': 'Терафія / Нальтіс',
    'era_threnody_year_uk': '~3500 ПР',
    'era_roshar_label_uk': 'Рошар · Архів Шторму Дуга 1',
    'era_roshar_year_uk': '1174–1175 СА',
    'era_scadrial2_label_uk': 'Скадріаль Ера 2',
    'era_scadrial2_year_uk': '~342 ВЕ',
    'era_future_label_uk': 'Далеке майбутнє · Таємні проекти',
    'era_future_year_uk': '~5000+ ПР',
  },
};

// Verified by fetching official source pages. null = no verified cover → styled card.
const COVER_URL = {
  'Elantris':              'https://i.mbooks.com.ua/media/books/161c2c84-8a17-4303-ac2e-e5abf60d51a0/covers/None/7401d02b18ff45898bd4e563a3ac97c9.jpeg',
  'The Final Empire':      'https://i.mbooks.com.ua/media/books/2af81b24-c976-4b86-a9ac-b3bec57d9b1c/covers/None/0b850cd7b0fc45faa5f15921cf0e947d.jpeg',
  'Well of Ascension':     'https://i.mbooks.com.ua/media/books/d45f4c0d-ecf9-427d-99d3-60d4e2a7df24/covers/None/2cbf8aaa7dda4ec380ddd64a10410cdd.jpeg',
  'Hero of Ages':          'https://i.mbooks.com.ua/media/books/aaccbe63-7236-49e2-941b-4376b7df2f94/covers/None/3b627d477e8b4792b962a44420e2c733.jpeg',
  'Secret History':        'https://i.mbooks.com.ua/media/books/2f52b041-cbd8-42e2-853c-0d32193fa7c8/covers/None/ebecb515590a4aab98c2544cd2f44bdf.jpeg',
  'The Way of Kings':      'https://i.mbooks.com.ua/media/books/00a5a802-6364-47e1-ba6e-3079e9c15b73/covers/None/b621c81cfb3e4f32a388021f86c25823.jpeg',
  'Words of Radiance':     'https://i.mbooks.com.ua/media/books/4207e7a1-1202-47ce-b1b8-ddf1629673bd/covers/None/91b148cfbe1b4929b6fb37dab072c660.jpeg',
  'Edgedancer':            'https://i.mbooks.com.ua/media/books/fb4e5e4d-94bc-41bd-8151-955ab423a9e9/covers/None/e45d6ba960f2441aab2506201a39048e.jpeg',
  'Oathbringer':           'https://i.mbooks.com.ua/media/books/0cdf0e50-c374-4bac-914b-22d3bc6f79fe/covers/None/daab0512f8fd46c8ad2373d8d5175e49.jpeg',
  'Rhythm of War':         'https://i.mbooks.com.ua/media/books/4b8d9ee1-ee46-42df-9334-051d4bcc6503/covers/None/912341de4182447b9fdd3b1029a35160.jpeg',
  'Wind and Truth':        'https://i.mbooks.com.ua/media/books/9f4bba51-264e-40c8-8f60-2794dfdfc912/covers/None/261e2a4592be418ea0afc5e594e84085.jpeg',
  'Warbreaker':            WP + 'thumb/6/63/BrandonSandersonWarbreakerBookCover.jpg/220px-BrandonSandersonWarbreakerBookCover.jpg',
  'Alloy of Law':          'https://i.mbooks.com.ua/media/books/65c43cbd-efe7-41e5-ac3d-c1a0d6acbd5c/covers/None/e77ab671efbd4ab682c2adda1fc87454.jpeg',
  'Shadows of Self':       'https://i.mbooks.com.ua/media/books/8a6ca8ed-00ab-4d37-82c1-d83ecbab97b2/covers/None/985cbfd322964b87baeb047c2a345086.jpeg',
  'Bands of Mourning':     'https://i.mbooks.com.ua/media/books/05e55f8c-f920-4b8b-977a-0fa6dc275fc2/covers/None/c1fede16a3d8494fa9e5ee75984dc9df.jpeg',
  'The Lost Metal':        'https://i.mbooks.com.ua/media/books/50f8d80c-8cd8-4025-adf3-c2649079d10d/covers/None/56286f95e3bf4176973ac7a0c39409d6.jpeg',
  'Tress of the Emerald Sea':  'https://i.mbooks.com.ua/media/books/29b2940c-45ab-4fca-98cb-2f779b9a82e7/covers/None/809b3429c9c8458b98d4a021db9f4357.jpeg',
  'Elsecaller':                'https://www.dragonsteelbooks.com/cdn/shop/files/DoubleBook1.jpg?v=1765301146',
  'King Lopen the First of Alethkar': 'https://uploads.coppermind.net/Cover-King-Lopen.png',
  'Yumi & Nightmare Painter':  BS + 'Untitled_design_24.png',
  'The Sunlit Man':            BS + 'Untitled_design_25.png',
  'Isles of the Emberdark':    BS + 'grounded_book_images_eb8cef98-9df2-4923-8003-53d7ea09b823.png',
};

const COVER_URL_UK = {
  'The Way of Kings':      'https://i.mbooks.com.ua/media/books/87a12eb8-c61b-463b-8f22-93cd2f37c2b3/covers/4250/48833729291c4f59a75dcbe591196541.jpeg',
  'Words of Radiance':     'https://i.mbooks.com.ua/media/books/01a82d7f-a686-4e20-a40e-0eac618bd9ad/covers/None/804af003495d4c0bb365090db4acea2f.jpeg',
  'Oathbringer':           'https://i.mbooks.com.ua/media/books/ebd16617-1c8d-423f-8b7a-f9f23969d39f/covers/None/1c20ac6a28bd450f891629b43dfb15fe.jpeg',
  'Rhythm of War':         'https://i.mbooks.com.ua/media/books/d9060b87-8b62-42e8-b584-b0a4700b23c0/covers/None/c450b095ca8e4cac903307bf39b9cb35.jpeg',
  'Wind and Truth':        'https://i.mbooks.com.ua/media/books/3e55792d-00ac-417b-a981-6065c045f6e8/covers/None/9a110307399f4f78a810bd2f5645f7bf.jpeg',
  'Warbreaker':            'https://i.mbooks.com.ua/media/books/e120a44c-03a4-4053-8a1b-1bd071f14b81/covers/None/65f29b4efe924f89bb7f195c39e27e63.jpeg',
};

const LOCALIZED_COVER_URLS = {
  uk: COVER_URL_UK,
};

const BOOK_TITLE_EN = {
  dragonsteel: 'Dragonsteel',
  theSilenceDivine: 'The Silence Divine',
  whiteSand: 'White Sand',
  elantris: 'Elantris',
  hopeOfElantris: 'Hope of Elantris',
  theEmperorsSoul: "The Emperor's Soul",
  elantrisBook2: 'Elantris Book 2',
  elantrisBook3: 'Elantris Book 3',
  theEleventhMetal: 'The Eleventh Metal',
  theFinalEmpire: 'The Final Empire',
  secretHistory: 'Secret History',
  wellOfAscension: 'Well of Ascension',
  heroOfAges: 'Hero of Ages',
  shadowsForSilence: 'Shadows for Silence',
  warbreaker: 'Warbreaker',
  theWayOfKings: 'The Way of Kings',
  wordsOfRadiance: 'Words of Radiance',
  edgedancer: 'Edgedancer',
  oathbringer: 'Oathbringer',
  dawnshard: 'Dawnshard',
  rhythmOfWar: 'Rhythm of War',
  windAndTruth: 'Wind and Truth',
  alloyOfLaw: 'Alloy of Law',
  allomancerJak: 'Allomancer Jak',
  shadowsOfSelf: 'Shadows of Self',
  bandsOfMourning: 'Bands of Mourning',
  theLostMetal: 'The Lost Metal',
  tressOfTheEmeraldSea: 'Tress of the Emerald Sea',
  yumiAndNightmarePainter: 'Yumi & Nightmare Painter',
  sixthOfTheDusk: 'Sixth of the Dusk',
  islesOfTheEmberdark: 'Isles of the Emberdark',
  theSunlitMan: 'The Sunlit Man',
  elsecaller: 'Elsecaller',
  kingLopenFirstOfAlethkar: 'King Lopen the First of Alethkar',
  horneater: 'Horneater',
  whiteSandProse: 'White Sand (Prose)',
  warbreakerSequel: 'Warbreaker Sequel',
  ghostbloodsBook1: 'Ghostbloods Book 1',
  ghostbloodsBook2: 'Ghostbloods Book 2',
  ghostbloodsBook3: 'Ghostbloods Book 3',
};

const PLANETS = {
  yolen:     { labelKey: 'yolen',     color: '#c9a84c' },
  taldain:   { labelKey: 'taldain',   color: '#7F77DD' },
  sel:       { labelKey: 'sel',       color: '#D4537E' },
  scadrial1: { labelKey: 'scadrial1', color: '#BA7517' },
  nalthis:   { labelKey: 'nalthis',   color: '#639922' },
  threnody:  { labelKey: 'threnody',  color: '#888780' },
  roshar:    { labelKey: 'roshar',    color: '#378ADD' },
  scadrial2: { labelKey: 'scadrial2', color: '#EF9F27' },
  lumar:     { labelKey: 'lumar',     color: '#5DCAA5' },
  komashi:   { labelKey: 'komashi',   color: '#F4C0D1' },
  fots:      { labelKey: 'fots',      color: '#993C1D' },
  canticle:  { labelKey: 'canticle',  color: '#B5D4F4' },
};

// x positions scaled 50% larger (originals × 1.5, rounded to nearest 5)
const BOOKS = [
  { titleKey: 'dragonsteel',         planet: 'yolen',     x: 105,  above: true,  stemH: 135, yearKey: 'dragonsteel_year',         blurbKey: 'dragonsteel_blurb', upcoming: true },
  { titleKey: 'theSilenceDivine',    planet: 'yolen',     x: 235,  above: false, stemH: 83,  yearKey: 'theSilenceDivine_year',    blurbKey: 'theSilenceDivine_blurb', upcoming: true },
  { titleKey: 'whiteSand',           planet: 'taldain',   x: 420,  above: true,  stemH: 120, yearKey: 'whiteSand_year',           blurbKey: 'whiteSand_blurb' },
  { titleKey: 'whiteSandProse',      planet: 'taldain',   x: 520,  above: false, stemH: 92,  yearKey: 'whiteSandProse_year',      blurbKey: 'whiteSandProse_blurb', upcoming: true },
  { titleKey: 'elantris',            planet: 'sel',       x: 608,  above: false, stemH: 98,  yearKey: 'elantris_year',            blurbKey: 'elantris_blurb' },
  { titleKey: 'hopeOfElantris',      planet: 'sel',       x: 720,  above: true,  stemH: 72,  yearKey: 'hopeOfElantris_year',      blurbKey: 'hopeOfElantris_blurb' },
  { titleKey: 'theEmperorsSoul',     planet: 'sel',       x: 833,  above: false, stemH: 83,  yearKey: 'theEmperorsSoul_year',     blurbKey: 'theEmperorsSoul_blurb' },
  { titleKey: 'elantrisBook2',       planet: 'sel',       x: 945,  above: true,  stemH: 98,  yearKey: 'elantrisBook2_year',       blurbKey: 'elantrisBook2_blurb', upcoming: true },
  { titleKey: 'elantrisBook3',       planet: 'sel',       x: 1058, above: false, stemH: 78,  yearKey: 'elantrisBook3_year',       blurbKey: 'elantrisBook3_blurb', upcoming: true },
  { titleKey: 'theEleventhMetal',    planet: 'scadrial1', x: 1245, above: true,  stemH: 78,  yearKey: 'theEleventhMetal_year',    blurbKey: 'theEleventhMetal_blurb' },
  { titleKey: 'theFinalEmpire',      planet: 'scadrial1', x: 1358, above: false, stemH: 210, yearKey: 'theFinalEmpire_year',      blurbKey: 'theFinalEmpire_blurb' },
  { titleKey: 'secretHistory',       planet: 'scadrial1', x: 1470, above: true,  stemH: 93,  yearKey: 'secretHistory_year',       blurbKey: 'secretHistory_blurb' },
  { titleKey: 'wellOfAscension',     planet: 'scadrial1', x: 1583, above: false, stemH: 87,  yearKey: 'wellOfAscension_year',     blurbKey: 'wellOfAscension_blurb' },
  { titleKey: 'heroOfAges',          planet: 'scadrial1', x: 1695, above: true,  stemH: 120, yearKey: 'heroOfAges_year',          blurbKey: 'heroOfAges_blurb' },
  { titleKey: 'shadowsForSilence',   planet: 'threnody',  x: 1860, above: false, stemH: 93,  yearKey: 'shadowsForSilence_year',   blurbKey: 'shadowsForSilence_blurb' },
  { titleKey: 'warbreaker',          planet: 'nalthis',   x: 1992, above: true,  stemH: 143, yearKey: 'warbreaker_year',          blurbKey: 'warbreaker_blurb' },
  { titleKey: 'warbreakerSequel',    planet: 'nalthis',   x: 2075, above: false, stemH: 108, yearKey: 'warbreakerSequel_year',    blurbKey: 'warbreakerSequel_blurb', upcoming: true },
  { titleKey: 'theWayOfKings',       planet: 'roshar',    x: 2157, above: false, stemH: 233, yearKey: 'theWayOfKings_year',       blurbKey: 'theWayOfKings_blurb' },
  { titleKey: 'wordsOfRadiance',     planet: 'roshar',    x: 2277, above: true,  stemH: 102, yearKey: 'wordsOfRadiance_year',     blurbKey: 'wordsOfRadiance_blurb' },
  { titleKey: 'edgedancer',          planet: 'roshar',    x: 2375, above: false, stemH: 87,  yearKey: 'edgedancer_year',          blurbKey: 'edgedancer_blurb' },
  { titleKey: 'oathbringer',         planet: 'roshar',    x: 2472, above: true,  stemH: 117, yearKey: 'oathbringer_year',         blurbKey: 'oathbringer_blurb' },
  { titleKey: 'dawnshard',           planet: 'roshar',    x: 2570, above: false, stemH: 78,  yearKey: 'dawnshard_year',           blurbKey: 'dawnshard_blurb' },
  { titleKey: 'elsecaller',          planet: 'roshar',    x: 2665, above: true,  stemH: 95,  yearKey: 'elsecaller_year',          blurbKey: 'elsecaller_blurb' },
  { titleKey: 'kingLopenFirstOfAlethkar', planet: 'roshar', x: 2760, above: false, stemH: 92, yearKey: 'kingLopenFirstOfAlethkar_year', blurbKey: 'kingLopenFirstOfAlethkar_blurb' },
  { titleKey: 'rhythmOfWar',         planet: 'roshar',    x: 2860, above: true,  stemH: 138, yearKey: 'rhythmOfWar_year',         blurbKey: 'rhythmOfWar_blurb' },
  { titleKey: 'windAndTruth',        planet: 'roshar',    x: 2970, above: false, stemH: 117, yearKey: 'windAndTruth_year',        blurbKey: 'windAndTruth_blurb' },
  { titleKey: 'horneater',           planet: 'roshar',    x: 3070, above: true,  stemH: 102, yearKey: 'horneater_year',           blurbKey: 'horneater_blurb', upcoming: true },
  { titleKey: 'alloyOfLaw',          planet: 'scadrial2', x: 3200, above: true,  stemH: 87,  yearKey: 'alloyOfLaw_year',          blurbKey: 'alloyOfLaw_blurb' },
  { titleKey: 'allomancerJak',       planet: 'scadrial2', x: 3300, above: false, stemH: 69,  yearKey: 'allomancerJak_year',       blurbKey: 'allomancerJak_blurb' },
  { titleKey: 'shadowsOfSelf',       planet: 'scadrial2', x: 3405, above: true,  stemH: 102, yearKey: 'shadowsOfSelf_year',       blurbKey: 'shadowsOfSelf_blurb' },
  { titleKey: 'bandsOfMourning',     planet: 'scadrial2', x: 3518, above: false, stemH: 78,  yearKey: 'bandsOfMourning_year',     blurbKey: 'bandsOfMourning_blurb' },
  { titleKey: 'theLostMetal',        planet: 'scadrial2', x: 3630, above: true,  stemH: 117, yearKey: 'theLostMetal_year',        blurbKey: 'theLostMetal_blurb' },
  { titleKey: 'ghostbloodsBook1',    planet: 'scadrial2', x: 3735, above: false, stemH: 93,  yearKey: 'ghostbloodsBook1_year',    blurbKey: 'ghostbloodsBook1_blurb', upcoming: true },
  { titleKey: 'ghostbloodsBook2',    planet: 'scadrial2', x: 3845, above: true,  stemH: 102, yearKey: 'ghostbloodsBook2_year',    blurbKey: 'ghostbloodsBook2_blurb', upcoming: true },
  { titleKey: 'ghostbloodsBook3',    planet: 'scadrial2', x: 3955, above: false, stemH: 87,  yearKey: 'ghostbloodsBook3_year',    blurbKey: 'ghostbloodsBook3_blurb', upcoming: true },
  { titleKey: 'tressOfTheEmeraldSea', planet: 'lumar',    x: 4070, above: false, stemH: 102, yearKey: 'tressOfTheEmeraldSea_year', blurbKey: 'tressOfTheEmeraldSea_blurb' },
  { titleKey: 'yumiAndNightmarePainter', planet: 'komashi',  x: 4190, above: true,  stemH: 123, yearKey: 'yumiAndNightmarePainter_year', blurbKey: 'yumiAndNightmarePainter_blurb' },
  { titleKey: 'sixthOfTheDusk',      planet: 'fots',     x: 4305, above: false, stemH: 93,  yearKey: 'sixthOfTheDusk_year',      blurbKey: 'sixthOfTheDusk_blurb' },
  { titleKey: 'islesOfTheEmberdark', planet: 'fots',     x: 4420, above: true,  stemH: 108, yearKey: 'islesOfTheEmberdark_year', blurbKey: 'islesOfTheEmberdark_blurb' },
  { titleKey: 'theSunlitMan',        planet: 'canticle', x: 4540, above: false, stemH: 135, yearKey: 'theSunlitMan_year',        blurbKey: 'theSunlitMan_blurb' },
];

const ERAS = [
  { x: 83,   labelKey: 'era_yolen_label',      yearKey: 'era_yolen_year' },
  { x: 398,  labelKey: 'era_taldain_label',    yearKey: 'era_taldain_year' },
  { x: 585,  labelKey: 'era_sel_label',        yearKey: 'era_sel_year' },
  { x: 1230, labelKey: 'era_scadrial1_label',  yearKey: 'era_scadrial1_year' },
  { x: 1838, labelKey: 'era_threnody_label',   yearKey: 'era_threnody_year' },
  { x: 2130, labelKey: 'era_roshar_label',     yearKey: 'era_roshar_year' },
  { x: 3180, labelKey: 'era_scadrial2_label',  yearKey: 'era_scadrial2_year' },
  { x: 4010, labelKey: 'era_future_label',     yearKey: 'era_future_year' },
];

const TOTAL_W = 4780;
const AXIS_Y  = 410;
